include:
  - svc_Chats/docker-compose.yml
  - svc_CompanyManagement/docker-compose.yml
  - svc_Auth/docker-compose.yml
  - svc_InterviewBack/docker-compose.yml
  - svc_ThirdCourseBack/docker-compose.yml
