services:
  interview:
    build:
      context: ./svc_InterviewBack
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - CONNECTION_STRING=Host=postgres;Port=5432;Database=interview;Username=postgres;Password=postgres
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interview
