include:
  - ../database/docker-compose.yml

services:
  third-course:
#    build:
#      context: .
    image: slakter/hitsinternsbackend-internship:latest
    ports:
      - '8091:8091'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  minio:
    image: bitnami/minio:2023.4.28
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminqwerty
    volumes:
      - minio-data:/data
    ports:
      - 9900:9000
      - 9901:9001

volumes:
  minio-data:
